using UnityEngine;
using UnityEngine.SceneManagement;
using Zenject;

public class GamePlayEntryPoint : MonoBehaviour
{
    public InGameStateMachine InGameStateMachine { get; private set; }

    [Inject]
    public void Construct(InGameStateMachine inGameStateMachine)
    {
        InGameStateMachine = inGameStateMachine;
    }

    private void Awake()
    {
        GameEntryPoint.Instance.Initialize();
    }

    public void LoadGame()
    {
        GameEntryPoint.Instance.LoadScene(SceneNamesStorage.AutoGeneratedLevelsSceneName);
    }

    public void LoadMenuScene()
    {
        GameEntryPoint.Instance.LoadScene(SceneNamesStorage.MenuSceneName);
    }

    public void RestartScene()
    {
        GameEntryPoint.Instance.LoadScene(SceneManager.GetActiveScene().name);
    }
}