public static class SceneNamesStorage
{
    public const string MenuSceneName = "Menu";
    public const string BootSceneName = "Boot";
    public const string AutoGeneratedLevelsSceneName = "AutoGeneratedLevels";
}
