using UnityEngine;

public class AutoGeneratedLevels : MonoBehaviour
{
    [SerializeField] private GameObject[] Levels;
    [SerializeField] private Vector3 InitialPosition = Vector3.zero;
    [SerializeField] private float StepBetweenLevels = 50;
    [SerializeField] private int LevelAmount = 50;

    [SerializeField] private GameObject FirstLevel;
    [SerializeField] private GameObject LastLevel;
    private void Awake()
    {
        LastLevel.transform.position = Vector3.zero;

        Vector3 _tempPosition = InitialPosition;
        GameObject _tempGameObject;

        _tempPosition.z += StepBetweenLevels;
        for (int i = 1; i < LevelAmount - 1; i++)
        {
            _tempGameObject = Levels[Random.Range(0, Levels.Length)];

            _tempGameObject = Instantiate(_tempGameObject);
            _tempGameObject.SetActive(true);

            _tempGameObject.transform.position = _tempPosition;
            _tempPosition.z += StepBetweenLevels;
        }

        FirstLevel.SetActive(true);

        LastLevel.SetActive(true);
        LastLevel.transform.position = _tempPosition;
    }
}
