using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class SceneLoader : MonoBehaviour
{
    [SerializeField] private Slider ProgressSlider;
    private AsyncOperation operation;
    private void Start()
    {
        ProgressSlider.value = 0;

        StartCoroutine(LoadScene());
    }
    public void StartLoading()
    {
        StartCoroutine(LoadScene());
    }
    IEnumerator LoadScene()
    {
        operation = SceneManager.LoadSceneAsync("AutoGeneratedLevels", LoadSceneMode.Single);
        while (!operation.isDone)
        {
            ProgressSlider.value = operation.progress;
            yield return null;
        }
    }    
}